apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Gusionling/dev-gitops
    targetRevision: HEAD
    path: manifests/go-web
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true